name=input("Enter name of the student ")
age=int(input("Enter age "))
degree=input("Enter Degree ")
fpl=input("Enter favorite Programming Language ")
cg=input("Enter Career Goal ")
print("-----Student Profile-----\n")
print("Name   :",name)
print("Age    :",age)
print("Degree :",degree)
print("Favoriate Programming Language :",fpl)
print("Career Goal :",cg)
print()
